project_id           = "beeping-platform-prod"
region               = "europe-west1"
auth_endpoint        = "https://europe-west1-beeping-platform-prod.cloudfunctions.net/validateApiKey"
cors_allowed_origins = "https://beeping.io"
custom_domain        = "beepbox.beeping.io"
