if (APPLE)
    message(STATUS "${BoldWhite}brew install libsndfile${ColourReset}")
elseif (UNIX)
    message(STATUS "${BoldWhite}sudo apt-get -y install libsndfile1${ColourReset}")
else()    
    message(STATUS "${BoldWhite}No command found${ColourReset}")
endif ()